# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet tool install --global dotnet-sonarscanner
  displayName: 'Install sonarscanner'
- script: dotnet sonarscanner begin /k:"NickHarvey2_Graph" /d:sonar.organization="nickharvey2-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(token)" /d:sonar.cs.vstest.reportsPaths=**/*.trx /d:sonar.cs.vscoveragexml.reportsPaths=**/*.coveragexml /d:sonar.exclusions="**/obj/**/*" /v:1.0.0
  displayName: Sonar Prepare
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test --collect:"Code Coverage" --logger trx --results-directory ./TestResults/
  displayName: 'dotnet test'